# https://github.com/actions/labeler
chore:
  - '*'
  - .github/**/*

docs:
  - docs/**/*

devops:
  - cmds/**/*
  - devops/**/*

frontend:
  - '**/*.js'
  - '**/*.ts'
  - '**/*.tsx'

backend:
  - '**/*.go'
  - '**/go.mod'
  - '**/go.sum'
