# https://github.com/actions/labeler

root:
- changed-files:
  - any-glob-to-any-file: '*'

# Add 'anychange' label to any changes within the entire repository
anychange:
- changed-files:
  - any-glob-to-any-file: '**'

chore:
  - changed-files:
    - any-glob-to-any-file: ['*', '.github/**/*']

docs:
  - /**/README*

devops:
  - changed-files:
    - any-glob-to-any-file: ['devops/**/*']

frontend:
  - changed-files:
    - any-glob-to-any-file: ['**/*.js', '**/*.ts', '**/*.tsx']

backend:
  - changed-files:
    - any-glob-to-any-file: ['**/go.sum', '**/*.go', '**/go.mod']

release:
 - base-branch: 'main'

dev-branch:
 - base-branch: 'dev'

source:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
